- name: Update comments.json
        run: |
          echo '{
            "landscape": {
              "00_main.webp": { "title": "${{ github.event.client_payload.t00 }}", "description": "${{ github.event.client_payload.d00 }}" },
              "01.webp": { "title": "${{ github.event.client_payload.t01 }}", "description": "${{ github.event.client_payload.d01 }}" },
              "02.webp": { "title": "${{ github.event.client_payload.t02 }}", "description": "${{ github.event.client_payload.d02 }}" }
            },
            "vertical": {
              "11.webp": { "title": "${{ github.event.client_payload.t11 }}", "description": "${{ github.event.client_payload.d11 }}" }
            }
          }' > Gallery/comments.json
